

SELECT column_name
FROM INFORMATION_SCHEMA.columns
WHERE table_schema = 'silver' 
  AND table_name = 'crm_cust_info';
  
  
  
  
SELECT 
ci.cst_create_date,
ci.cst_firstname,
ci.cst_gndr,
ci.cst_id,
ci.cst_key,
ci.cst_lastname,
ci.cst_marital_status,
ci.dwh_create_date
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid;


-- next step
SELECT 
ci.cst_id,
ci.cst_key,
ci.cst_create_date,
ci.cst_firstname,
ci.cst_gndr,
ci.cst_lastname,
ci.cst_marital_status,
ci.dwh_create_date,
ca.bdate,
ca.gen,
la.cntry
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid;



-- after joining the tables , we have to check that we have duplicate values in pm_key


SELECT cst_id, COUNT(*)
FROM 
(
SELECT 
ci.cst_id,
ci.cst_key,
ci.cst_create_date,
ci.cst_firstname,
ci.cst_gndr,
ci.cst_lastname,
ci.cst_marital_status,
ci.dwh_create_date,
ca.bdate,
ca.gen,
la.cntry
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid
) t
GROUP BY cst_id
HAVING COUNT(*) > 1;


-- issue 1: we have two sources for gender: cst_gender and gen


SELECT
DISTINCT 
ci.cst_gndr,
ca.gen   
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid;



-- solution: consider crm is the master table , and source of truth , so consider cst_gender as correct 
-- if the cst_gender is n/a , then consider gen of erp table as source of truth (with COALSES FUNC to handle NULL)

SELECT 
ci.cst_gndr,
ca.gen,
CASE 
   WHEN ci.cst_gndr!=	'n/a' THEN ci.cst_gndr
   ELSE COALESCE(ca.gen , 'n/a')
END AS new_gen      
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid;


-- rename the columns to be business friendly , following snake_case rules

SELECT 
ci.cst_id AS customer_id,
ci.cst_key AS customer_number,
ci.cst_firstname AS first_name,
ci.cst_lastname AS last_name,
la.cntry AS country,
ci.cst_marital_status AS martial_status,
CASE 
   WHEN ci.cst_gndr!=	'n/a' THEN ci.cst_gndr
   ELSE COALESCE(ca.gen , 'n/a')
END AS gender,
ca.bdate AS birthdate,
ci.cst_create_date AS create_date    
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid;


-- this table is dimension/ fact table?

-- ETL usually happens before and during the loading of data into the Data Warehouse

-- we have to  introduce a pm_key before putting this table in data warehouse

/*

A surrogate key is a unique key generated by the Data Warehouse itself, rather than 
coming from the source system.

In simple terms:

Surrogate key = artificial/internal ID created by the warehouse to uniquely identify a record.

Example:

Suppose your source CRM has:

customer_id | name   | city
------------|--------|--------
101         | Rahul  | Chennai
102         | Anirudh| Bangalore

Here customer_id is the source/business key.

When loading into the warehouse, you might create:

PM_KEY | customer_id | name    | city
-------|-------------|---------|--------
1      | 101         | Rahul   | Chennai
2      | 102         | Anirudh | Bangalore

Here:

customer_id → Natural/Business Key
PM_KEY → Surrogate Key

The warehouse generated 1 and 2; the source system didn't provide them.


Natural Key vs Surrogate Key

|              | Natural/Business Key      | Surrogate Key               |
| ------------ | ------------------------- | --------------------------- |
| Comes from   | Source system             | Data Warehouse              |
| Example      | `customer_id = 101`       | `PM_KEY = 1`                |
| Meaning      | Has business meaning      | Usually no business meaning |
| Generated by | Source                    | Warehouse/ETL               |
| Used for     | Identifying source record | Warehouse relationships     |




*/





/*

often we introduce a PM_KEY (primary/surrogate key) before or while loading a dimension table into the Data Warehouse, 
but it depends on the table and warehouse design.

For a typical dimension table, the flow is:

Source Customer Table
        ↓
   Extract
        ↓
   Staging/Bronze
        ↓
 Transform/Clean
        ↓
 Generate PM_KEY
        ↓
 Data Warehouse Dimension
 
Example:

Suppose the source has:

customer_id | name    | city
------------|---------|--------
101         | Rahul   | Chennai
102         | Anirudh | Bangalore

You might create the warehouse dimension as:

PM_KEY | customer_id | name    | city
-------|-------------|---------|----------
1      | 101         | Rahul   | Chennai
2      | 102         | Anirudh | Bangalore

Here:

customer_id → Business/Natural Key coming from the source.
PM_KEY → Surrogate key generated by the warehouse.
PM_KEY is typically the primary key of the dimension table.
Why introduce PM_KEY?

The main reason is that source-system IDs aren't always suitable as warehouse keys.

For example, you could have:

CRM:
customer_id = 101

ERP:
customer_id = 101

Those might represent different entities.
Also, source IDs can change, while the warehouse surrogate key can remain stable.

Very important: Facts use the PM_KEY

Suppose you have:

Dimension:

dim_customer

PM_KEY | customer_id | name
-------|-------------|-------
1      | 101         | Rahul
2      | 102         | Anirudh


Fact:

fact_sales

sales_id | customer_PM_KEY | amount
---------|------------------|-------
5001     | 1                | 10000
5002     | 2                | 15000

So the relationship becomes:

dim_customer
     │
     │ PM_KEY
     ↓
fact_sales

This is one of the important concepts behind a star schema.

One correction to your wording

Don't think:
"Every table must get a PM_KEY before entering the Data Warehouse."

Instead think:
Dimension tables commonly receive a surrogate/PM key, and fact tables store those dimension keys as foreign keys.

For example:

                  DATA WAREHOUSE

             ┌─────────────────┐
             │  dim_customer   │
             │-----------------│
             │ PM_KEY          │
             │ customer_id     │
             │ customer_name   │
             └────────┬────────┘
                      │
                      │ PM_KEY
                      ↓
             ┌─────────────────┐
             │   fact_sales    │
             │-----------------│
             │ sales_key       │
             │ customer_PM_KEY │
             │ product_PM_KEY  │
             │ date_PM_KEY     │
             │ sales_amount    │
             └─────────────────┘

If ETL project has Business Objects → Facts → Dimensions → Integration Model, 
then PM_KEY is particularly important because it is usually part of how the dimension and fact relationships are established.


*/

-- create object type views for gold layer

CREATE VIEW gold.dim_customers AS
SELECT 
ROW_NUMBER() OVER(ORDER BY cst_id) AS customer_key,	
ci.cst_id AS customer_id,
ci.cst_key AS customer_number,
ci.cst_firstname AS first_name,
ci.cst_lastname AS last_name,
la.cntry AS country,
ci.cst_marital_status AS martial_status,
CASE 
   WHEN ci.cst_gndr!=	'n/a' THEN ci.cst_gndr
   ELSE COALESCE(ca.gen , 'n/a')
END AS gender,
ca.bdate AS birthdate,
ci.cst_create_date AS create_date    
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
ON   ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
ON    ci.cst_key = la.cid;

DROP VIEW gold.dim_customer;


/*

The Gold layer is creating a view because 
`gold.dim_customer` is a business-ready representation of data that already exists in Silver.

Let's break your exact code down.

 1. What your view is doing

You have three Silver tables:


silver.crm_cust_info
silver.erp_cust_az12
silver.erp_loc_a101


Your Gold view combines them:


                 Silver Layer
                     │
        ┌────────────┼────────────┐
        ↓            ↓            ↓
 crm_cust_info   erp_cust_az12  erp_loc_a101
        │            │            │
        └────────────┼────────────┘
                     ↓
                 Gold View
              gold.dim_customer
                     ↓
              BI / Analytics


So `gold.dim_customer` presents the customer data in a business-friendly format.

---

 Why use a VIEW in Gold?

 1. Gold is supposed to be business-ready

Your Silver tables are still organized around source systems:


crm_cust_info
erp_cust_az12
erp_loc_a101


But the business doesn't want to think about three different source tables.

They want:
dim_customer


with:

customer_key
customer_id
customer_number
first_name
last_name
country
marital_status
gender
birthdate
create_date


The view gives them exactly that.

---

 2. It combines multiple Silver tables

Your query:

FROM silver.crm_cust_info ci

LEFT JOIN silver.erp_cust_az12 ca
    ON ci.cst_key = ca.cid

LEFT JOIN silver.erp_loc_a101 la
    ON ci.cst_key = la.cid;


creates one logical customer dimension from three different sources.

So instead of a BI developer writing:


JOIN
JOIN
CASE
COALESCE


every time, they can simply do:

sql
SELECT *
FROM gold.dim_customer;


---

 3. It applies business logic

For example, your gender logic:


CASE 
    WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr
    ELSE COALESCE(ca.gen, 'n/a')
END AS gender


means:

> If CRM has a valid gender, use it. Otherwise, get the gender from ERP. If that is also unavailable, 
use `'n/a'`.

That's business logic, which is exactly the kind of logic commonly exposed in the Gold layer.

---

 4. It creates a surrogate key

You have:


ROW_NUMBER() OVER(ORDER BY cst_id) AS customer_key


This generates:


customer_key
------------
1
2
3
4
...


This is acting as your surrogate key for the dimension.

So your Gold dimension becomes:


gold.dim_customer

customer_key | customer_id | customer_number | first_name
-------------|-------------|-----------------|-----------
1            | 101         | C001            | Rahul
2            | 102         | C002            | Anirudh
3            | 103         | C003            | John


---

 But there is an important point about your `ROW_NUMBER()`

Because this is a VIEW, the `customer_key` isn't physically stored.

Every time you query the view, MySQL calculates:


ROW_NUMBER() OVER(ORDER BY cst_id) again.

For example:


SELECT *
FROM gold.dim_customer;


MySQL calculates the row numbers at query time.

Therefore, using `ROW_NUMBER()` as a permanent warehouse surrogate key can be problematic if records are inserted/deleted or the ordering changes.

In a production data warehouse, you would commonly have a physical dimension table:


gold.dim_customer and generate/store a surrogate key such as:

customer_key BIGINT AUTO_INCREMENT
or generate it during the ETL/ELT process.

---

 View vs Table

This is the important distinction:

 VIEW:

CREATE VIEW gold.dim_customer AS
SELECT ...


A view generally stores the SQL definition, not a separate copy of the result data.


Silver tables
     ↓
   VIEW
     ↓
Result calculated when queried


TABLE:

CREATE TABLE gold.dim_customer AS
SELECT ...


The resulting rows are physically stored.


Silver tables
     ↓
 ETL / ELT
     ↓
Gold table
     ↓
Stored physically


---

 So why might your project use a Gold VIEW?

If this is a learning/data-warehouse project, using a view is convenient because:


Silver
  ↓
JOIN + business logic
  ↓
Gold VIEW
  ↓
Analytics


we don't have to physically copy the data into another table.

It also means when Silver data changes, the Gold view can reflect those changes automatically when queried.

---

 Your architecture is basically


             SOURCE SYSTEMS
        ┌─────────┼─────────┐
        ↓         ↓         ↓
       CRM       ERP       ERP
        │         │         │
        └─────────┼─────────┘
                  ↓
             BRONZE/RAW
                  ↓
             SILVER LAYER
        ┌─────────┼─────────┐
        ↓         ↓         ↓
 crm_cust_info  cust_az12  loc_a101
        │         │         │
        └─────────┼─────────┘
                  ↓
          Business Logic
       JOIN / CASE / COALESCE
                  ↓
             GOLD LAYER
                  ↓
          dim_customer VIEW
                  ↓
           BI / Reporting


In one sentence:

We create a Gold view to expose cleaned, integrated, business-ready data in a convenient structure 
without necessarily creating another physical copy of the Silver data.

And one thing to keep in mind: Gold does not have to be a view. In production warehouses, 
Gold dimensions/facts are very often physical tables, especially when you need stable surrogate keys, 
historical tracking, performance, and incremental loading.



*/


SELECT * FROM  gold.dim_customer;




  